#!/usr/bin/env python3
"""Build the static documentation site, and keep its generated pages from drifting.

The site is built from the Markdown under docs/ and developer-docs/ with the standard library only: a left navigation, no search, no JavaScript, light and dark by the reader's system setting. The landing page and the first-run load page come from docs/site-source/ and scripts/docs/templates/.

Two pages are generated from the code so they cannot drift from it: the command reference from the argparse tree of `stratarc.cli`, and the error catalog from `stratarc.messages`. They are committed under docs/reference/generated/.

    build_site.py                    build the site into site/
    build_site.py --out DIR          build into DIR
    build_site.py --write-generated  rewrite the committed generated pages
    build_site.py --check            exit 6 when a committed generated page differs

This is a development tool. It is not part of the installed package.

Exit statuses: 0 ok, 1 build failure (a broken link, a failed capture), 2 invalid input, 6 a committed generated page differs from the code.
"""

from __future__ import annotations

import argparse
import html
import importlib
import os
import posixpath
import re
import shutil
import string
import subprocess
import sys
import tempfile
from pathlib import Path

ENGINE_ROOT = Path(__file__).resolve().parents[2]
TEMPLATES = Path(__file__).resolve().parent / "templates"
if str(ENGINE_ROOT) not in sys.path:
    sys.path.insert(0, str(ENGINE_ROOT))
sys.dont_write_bytecode = True
GENERATED_DIR = "docs/reference/generated"
SITE_SOURCE = "docs/site-source"
SECTIONS = (("docs", "documentation"), ("developer-docs", "developer documentation"))
QUADRANTS = ("tutorials", "how-to-guides", "reference", "explanation")
REPO_URL = "https://github.com/klappe-pm/stratarc"
GENERATED_NOTE = "<!-- generated by scripts/docs/build_site.py from the code; do not edit by hand -->"

# The captured example on the landing page. It runs the engine against the bundled example, so the page shows what the command really prints.
CAPTURE_ARGS = ["config", "explain", "permissions.defaultMode", "--project", "notes-cli", "--root", "examples/notes-cli/source"]
CAPTURE_SHOWN = "stratarc " + " ".join(CAPTURE_ARGS)

EXIT_STATUS_ROWS = (
    (0, "ok"),
    (1, "failure: the command ran and did not succeed"),
    (2, "invalid input: a bad argument, an unknown source root, an invalid `stratarc.toml`, or a refusal by the engine"),
    (3, "denied: the home is missing or not writable"),
    (4, "conflict: the target already holds something"),
    (5, "unavailable: a packaged resource is missing, a file in the home is newer than this stratarc, a provider did not answer, an adapter does not support the installed runtime, or the change log database is locked"),
    (6, "drift: the deployed files differ from what the source renders"),
    (130, "interrupted"),
)

# Resource parsers that live in the modules that own them: (command, module, factory). A parser that cannot be loaded is listed by its summary line only.
RESOURCE_PARSERS = (
    ("config", "stratarc.config_cmd", "_parser"),
    ("log", "stratarc.log_cmd", "_log_parser"),
    ("verify", "stratarc.log_cmd", "_verify_parser"),
    ("provider", "stratarc.providers", "_parser"),
    ("adapter", "stratarc.registry", "_parser"),
)


class BuildError(Exception):
    """A failure that stops the build with exit status 1."""


# ----- generated pages -----


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def _cell(text: str) -> str:
    return text.replace("|", "&#124;").replace("\n", " ")


def _sentence(text: str | None) -> str:
    """The help text as a sentence that ends in a full stop, or an empty string."""
    text = (text or "").strip()
    if not text:
        return ""
    text = text.replace("; repeatable", ". Repeatable")
    return text[0].upper() + text[1:] if text.endswith(".") else text[0].upper() + text[1:] + "."


def _table(header: list[str], rows: list[list[str]]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join("---" for _ in header) + " |"]
    lines += ["| " + " | ".join(_cell(c) for c in row) + " |" for row in rows]
    return lines


def _subparsers_action(parser: argparse.ArgumentParser) -> argparse._SubParsersAction | None:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _children(parser: argparse.ArgumentParser) -> list[tuple[str, str, argparse.ArgumentParser]]:
    """The (name, help, parser) of each subcommand, in the order they were registered."""
    action = _subparsers_action(parser)
    if action is None:
        return []
    helps = {choice.dest: (choice.help or "") for choice in action._choices_actions}
    return [(name, helps.get(name, ""), sub) for name, sub in action.choices.items()]


def _option_label(action: argparse.Action) -> str:
    flags = ", ".join(f"`{s}`" for s in action.option_strings)
    if action.nargs == 0:
        return flags
    metavar = action.metavar or action.dest.upper()
    return f"{flags} `{metavar}`"


def _own_options(parser: argparse.ArgumentParser, skip: set[str]) -> list[argparse.Action]:
    out = []
    for action in parser._actions:
        if isinstance(action, (argparse._HelpAction, argparse._VersionAction, argparse._SubParsersAction)):
            continue
        if not action.option_strings or action.help == argparse.SUPPRESS:
            continue
        if set(action.option_strings) & skip:
            continue
        out.append(action)
    return out


def _positionals(parser: argparse.ArgumentParser) -> list[argparse.Action]:
    return [a for a in parser._actions if not a.option_strings and not isinstance(a, argparse._SubParsersAction)]


def _usage(path: str, parser: argparse.ArgumentParser, skip: set[str]) -> str:
    parts = [path]
    kids = _children(parser)
    if kids:
        parts.append("{" + ",".join(name for name, _, _ in kids) + "}")
    for action in _positionals(parser):
        name = action.metavar or action.dest
        if action.choices and not action.metavar:
            name = "{" + ",".join(str(c) for c in action.choices) + "}"
        optional = action.nargs in ("?", "*")
        parts.append(f"[{name}]" if optional else name)
    for action in _own_options(parser, skip):
        flag = action.option_strings[0]
        if action.nargs == 0:
            parts.append(f"[{flag}]")
        else:
            parts.append(f"[{flag} {action.metavar or action.dest.upper()}]")
    return " ".join(parts)


def _arguments_block(parser: argparse.ArgumentParser, skip: set[str]) -> list[str]:
    lines: list[str] = []
    positionals = _positionals(parser)
    if positionals:
        rows = []
        for action in positionals:
            name = action.metavar or action.dest
            detail = _sentence(action.help)
            if action.choices:
                detail = (detail + " " if detail else "") + "One of " + ", ".join(f"`{c}`" for c in action.choices) + "."
            rows.append([f"`{name}`", detail])
        lines += ["", *_table(["argument", "meaning"], rows)]
    options = _own_options(parser, skip)
    if options:
        rows = []
        for a in options:
            detail = _sentence(a.help)
            if isinstance(a, argparse._AppendAction) and "repeatable" not in detail.lower():
                detail = (detail + " " if detail else "") + "Repeatable."
            rows.append([_option_label(a), detail])
        lines += ["", *_table(["option", "meaning"], rows)]
    return lines


def _load_resource_parser(module: str, factory: str) -> argparse.ArgumentParser | None:
    try:
        parser = getattr(importlib.import_module(module), factory)()
    except Exception:  # a renamed or broken factory leaves the summary line in place
        return None
    return parser if isinstance(parser, argparse.ArgumentParser) else None


def _command_section(name: str, summary: str, parser: argparse.ArgumentParser | None, global_flags: set[str]) -> list[str]:
    lines = ["", f"## {name}", ""]
    if parser is None:
        lines.append(summary + ".")
        lines += ["", f"This command forwards its arguments to its own parser. Run `stratarc {name} --help` for them."]
        return lines
    lines.append((summary or (parser.description or "")).rstrip(".") + ".")
    lines += ["", "```text", _usage(f"stratarc {name}", parser, global_flags), "```"]
    lines += _arguments_block(parser, global_flags)
    for child, child_help, child_parser in _children(parser):
        inherited = global_flags | {s for a in _own_options(parser, set()) for s in a.option_strings}
        lines += ["", f"### {name}-{child}", "", (child_help or "").rstrip(".") + ".", "", "```text", _usage(f"stratarc {name} {child}", child_parser, inherited), "```"]
        lines += _arguments_block(child_parser, inherited)
    return lines


def generate_commands_page() -> str:
    from stratarc import cli

    parser = cli.build_parser()
    global_group = next(g for g in parser._action_groups if g.title == "global options")
    global_actions = [a for a in global_group._group_actions]
    global_flags = {s for a in global_actions for s in a.option_strings}
    resources = {name: _load_resource_parser(module, factory) for name, module, factory in RESOURCE_PARSERS}

    summary_rows = []
    sections: list[str] = []
    for name, help_text, sub in _children(parser):
        summary_rows.append([f"[`{name}`](#{slug(name)})", help_text])
        has_own = any(not isinstance(a, argparse._HelpAction) for a in sub._actions) or _children(sub)
        chosen = sub if has_own else resources.get(name)
        sections += _command_section(name, help_text, chosen, global_flags)

    lines = [
        "# commands",
        "",
        GENERATED_NOTE,
        "",
        "Every command of `stratarc`, generated from the command line parser so the page cannot drift from the code. Run `python3 scripts/docs/build_site.py --check` to confirm it still matches.",
        "",
        "## global-options",
        "",
        "Global options are accepted before or after the command.",
        "",
        *_table(["option", "meaning"], [[_option_label(a), a.help or ""] for a in global_actions]),
        "",
        "## exit-statuses",
        "",
        *_table(["status", "meaning"], [[str(code), text] for code, text in EXIT_STATUS_ROWS]),
        "",
        "## command-list",
        "",
        *_table(["command", "summary"], summary_rows),
        *sections,
    ]
    return "\n".join(lines) + "\n"


def generate_errors_page() -> str:
    from stratarc import messages

    status_names = {
        messages.FAILURE: "failure",
        messages.INVALID_INPUT: "invalid-input",
        messages.DENIED: "denied",
        messages.CONFLICT: "conflict",
        messages.UNAVAILABLE: "unavailable",
        messages.DRIFT: "drift",
        messages.INTERRUPTED: "interrupted",
    }
    codes_by_id: dict[str, list[str]] = {}
    for code, message_id in messages.CODE_MESSAGES.items():
        codes_by_id.setdefault(message_id, []).append(code)

    catalog = sorted(messages.CATALOG.values(), key=lambda m: m.id)
    lines = [
        "# errors",
        "",
        GENERATED_NOTE,
        "",
        "Every message the command line can print, generated from `stratarc/messages.py`. Each message has an id, and the command line links to the entry with the same id on this page. A placeholder in braces, such as `{path}`, is filled in by the command.",
        "",
        "## message-list",
        "",
        *_table(
            ["id", "status", "problem"],
            [[f"[`{m.id}`](#{m.id})", f"{m.exit} {status_names.get(m.exit, '')}".strip(), m.problem] for m in catalog],
        ),
        "",
        "## messages",
    ]
    for m in catalog:
        lines += [
            "",
            f"### {m.id}",
            "",
            f"Ends the command with status {m.exit} ({status_names.get(m.exit, 'ok')}).",
            "",
            f"Problem: {m.problem}",
            "",
            f"Recovery: {m.recovery}",
        ]
        codes = codes_by_id.get(m.id)
        if codes:
            lines += ["", "Raised for the module " + ("code " if len(codes) == 1 else "codes ") + ", ".join(f"`{c}`" for c in sorted(codes)) + "."]
    return "\n".join(lines) + "\n"


def generated_pages() -> dict[str, str]:
    """The generated pages by repository-relative path."""
    return {
        f"{GENERATED_DIR}/commands.md": generate_commands_page(),
        f"{GENERATED_DIR}/errors.md": generate_errors_page(),
    }


def write_generated(repo: Path) -> list[str]:
    written = []
    for rel, text in generated_pages().items():
        target = repo / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.exists() or target.read_text(encoding="utf-8") != text:
            target.write_text(text, encoding="utf-8")
            written.append(rel)
    return written


def check_generated(repo: Path) -> list[str]:
    """The generated pages whose committed copy is missing or differs from the code."""
    stale = []
    for rel, text in generated_pages().items():
        target = repo / rel
        if not target.exists() or target.read_text(encoding="utf-8") != text:
            stale.append(rel)
    return stale


# ----- markdown -----

_INLINE_CODE = re.compile(r"(`+)(.+?)\1")
_LINK = re.compile(r"\[([^\]]+)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
_BOLD = re.compile(r"\*\*(.+?)\*\*")
_ITALIC = re.compile(r"(?<![\w*])\*(?!\s)(.+?)(?<!\s)\*(?![\w*])")
_LIST_ITEM = re.compile(r"^(\s*)([-*]|\d+\.)\s+(.*)$")


class Renderer:
    """Turns one Markdown file into an HTML fragment, resolving links through `resolve`."""

    def __init__(self, source: str, resolve):
        self.source = source
        self.resolve = resolve
        self.ids: set[str] = set()
        self.title = ""

    def unique_id(self, text: str) -> str:
        base = slug(text) or "section"
        candidate, n = base, 2
        while candidate in self.ids:
            candidate = f"{base}-{n}"
            n += 1
        self.ids.add(candidate)
        return candidate

    def inline(self, text: str) -> str:
        parts = []
        position = 0
        for match in _INLINE_CODE.finditer(text):
            parts.append(self._inline_text(text[position:match.start()]))
            parts.append(f"<code>{html.escape(match.group(2).strip(), quote=False)}</code>")
            position = match.end()
        parts.append(self._inline_text(text[position:]))
        return "".join(parts)

    def _inline_text(self, text: str) -> str:
        stash: list[str] = []

        def link(match: re.Match) -> str:
            label, target = match.group(1), match.group(2)
            stash.append(f'<a href="{html.escape(self.resolve(self.source, target), quote=True)}">{self._inline_text(label)}</a>')
            return f"\x00{len(stash) - 1}\x00"

        text = _LINK.sub(link, text)
        text = html.escape(text, quote=False)
        text = _BOLD.sub(r"<strong>\1</strong>", text)
        text = _ITALIC.sub(r"<em>\1</em>", text)
        return re.sub(r"\x00(\d+)\x00", lambda m: stash[int(m.group(1))], text)

    def render(self, text: str) -> str:
        lines = text.splitlines()
        out: list[str] = []
        i = 0
        while i < len(lines):
            line = lines[i]
            stripped = line.strip()
            if not stripped:
                i += 1
            elif stripped.startswith("<!--"):
                while i < len(lines) and "-->" not in lines[i]:
                    i += 1
                i += 1
            elif stripped.startswith("```"):
                lang = stripped[3:].strip()
                i += 1
                body = []
                while i < len(lines) and not lines[i].strip().startswith("```"):
                    body.append(lines[i])
                    i += 1
                i += 1
                cls = f' class="language-{html.escape(lang)}"' if lang else ""
                out.append(f"<pre><code{cls}>{html.escape(chr(10).join(body), quote=False)}</code></pre>")
            elif re.match(r"^#{1,6}\s", stripped):
                level = len(stripped) - len(stripped.lstrip("#"))
                heading = stripped[level:].strip()
                ident = self.unique_id(re.sub(r"[`*]", "", heading))
                if level == 1 and not self.title:
                    self.title = re.sub(r"[`*]", "", heading)
                out.append(f'<h{level} id="{ident}">{self.inline(heading)}</h{level}>')
                i += 1
            elif stripped.startswith("|") and i + 1 < len(lines) and re.match(r"^\s*\|?\s*:?-{3,}", lines[i + 1]):
                block = []
                while i < len(lines) and lines[i].strip().startswith("|"):
                    block.append(lines[i])
                    i += 1
                out.append(self._table(block))
            elif stripped.startswith(">"):
                block = []
                while i < len(lines) and lines[i].strip().startswith(">"):
                    block.append(lines[i].strip()[1:].strip())
                    i += 1
                out.append(f"<blockquote>{self.render(chr(10).join(block))}</blockquote>")
            elif _LIST_ITEM.match(line):
                block = []
                base_indent = len(_LIST_ITEM.match(line).group(1))
                while i < len(lines):
                    current = lines[i]
                    if current.strip():
                        if not (_LIST_ITEM.match(current) or current.startswith(" ")):
                            break
                        # a less indented list item ends this list
                        item = _LIST_ITEM.match(current)
                        if item and len(item.group(1)) < base_indent:
                            break
                    else:
                        following = next((l for l in lines[i + 1:] if l.strip()), "")
                        item = _LIST_ITEM.match(following)
                        if not following or not (following.startswith(" ") or (item and len(item.group(1)) >= base_indent)):
                            break
                    block.append(current)
                    i += 1
                out.append(self._list(block))
            else:
                block = []
                while i < len(lines) and lines[i].strip() and not re.match(r"^(#{1,6}\s|```|\||>)", lines[i].strip()) and not _LIST_ITEM.match(lines[i]):
                    block.append(lines[i].strip())
                    i += 1
                if not block:  # a lone line the other rules did not take
                    block = [lines[i].strip()]
                    i += 1
                out.append(f"<p>{self.inline(' '.join(block))}</p>")
        return "\n".join(out)

    def _table(self, block: list[str]) -> str:
        def cells(row: str) -> list[str]:
            row = row.strip()
            row = row[1:] if row.startswith("|") else row
            row = row[:-1] if row.endswith("|") else row
            return [c.strip().replace("&#124;", "|") for c in re.split(r"(?<!\\)\|", row)]

        head = cells(block[0])
        body = [cells(r) for r in block[2:]]
        th = "".join(f"<th>{self.inline(c)}</th>" for c in head)
        trs = "".join("<tr>" + "".join(f"<td>{self.inline(c)}</td>" for c in row) + "</tr>" for row in body)
        return f'<div class="table-wrap"><table><thead><tr>{th}</tr></thead><tbody>{trs}</tbody></table></div>'

    def _list(self, block: list[str]) -> str:
        first = _LIST_ITEM.match(block[0])
        assert first
        base = len(first.group(1))
        tag = "ol" if first.group(2)[0].isdigit() else "ul"
        items: list[list[str]] = []
        widths: list[int] = []
        for line in block:
            m = _LIST_ITEM.match(line)
            if m and len(m.group(1)) == base:
                items.append([m.group(3)])
                widths.append(base + len(m.group(2)) + 1)
            elif items:
                items[-1].append(line)
        rendered = []
        for item, width in zip(items, widths):
            head, rest = item[0], item[1:]
            inner = self.inline(head)
            if any(r.strip() for r in rest):
                nested = [r[width:] if r.startswith(" " * width) else r.lstrip() for r in rest]
                inner += "\n" + self.render("\n".join(nested))
            rendered.append(f"<li>{inner}</li>")
        return f"<{tag}>\n" + "\n".join(rendered) + f"\n</{tag}>"


# ----- the site -----


class Site:
    def __init__(self, repo: Path, out: Path, capture_root: Path | None = None):
        self.repo = repo
        self.out = out
        self.capture_root = capture_root or repo
        self.pages: dict[str, dict] = {}  # source path -> {out, title, html, ids, section}
        self.errors: list[str] = []

    # source discovery

    def out_path(self, source: str) -> str:
        if source == SITE_SOURCE + "/index.md":
            return "index.html"
        path = Path(source)
        if path.name == "README.md":
            return str(path.parent / "index.html")
        return str(path.with_suffix(".html"))

    def discover(self) -> list[str]:
        found = []
        for section, _ in SECTIONS:
            base = self.repo / section
            if not base.is_dir():
                continue
            for path in sorted(base.rglob("*.md")):
                rel = path.relative_to(self.repo).as_posix()
                if rel.startswith(SITE_SOURCE + "/") and rel != SITE_SOURCE + "/index.md":
                    continue
                found.append(rel)
        return found

    # link resolution

    def resolve(self, source: str, target: str) -> str:
        if re.match(r"^[a-z][a-z0-9+.-]*:", target, re.I):
            return target
        path, _, fragment = target.partition("#")
        suffix = f"#{fragment}" if fragment else ""
        if not path:
            return suffix or "#"
        joined = posixpath.normpath(posixpath.join(posixpath.dirname(source), path))
        here = self.out_path(source)
        if joined == "load.html":
            return posixpath.relpath("load.html", posixpath.dirname(here) or ".") + suffix
        candidates = [joined, posixpath.join(joined, "README.md")]
        for candidate in candidates:
            if candidate in self.known:
                return posixpath.relpath(self.out_path(candidate), posixpath.dirname(here) or ".") + suffix
        if joined.startswith(".."):
            self.errors.append(f"{source}: link {target} leaves the repository")
            return target
        full = self.repo / joined
        if full.is_dir():
            return f"{REPO_URL}/tree/main/{joined}"
        if full.exists():
            return f"{REPO_URL}/blob/main/{joined}"
        self.errors.append(f"{source}: link {target} does not resolve")
        return target

    # capture

    def capture(self) -> str:
        env = dict(os.environ)
        env["PYTHONPATH"] = str(ENGINE_ROOT)
        env["PYTHONDONTWRITEBYTECODE"] = "1"
        env["NO_COLOR"] = "1"
        with tempfile.TemporaryDirectory() as home:
            env["STRATARC_HOME"] = home
            result = subprocess.run([sys.executable, "-m", "stratarc", *CAPTURE_ARGS], cwd=self.capture_root, env=env, capture_output=True, text=True)
        if result.returncode != 0:
            raise BuildError(f"the captured example failed with exit {result.returncode}: {result.stderr.strip()}")
        text = result.stdout.rstrip("\n")
        if any(marker in text for marker in ("/" + "Users" + "/", "/home/", str(self.capture_root))):
            raise BuildError("the captured example contains a machine path")
        return f"```text\n$ {CAPTURE_SHOWN}\n{text}\n```"

    # build

    def build(self) -> None:
        sources = self.discover()
        self.known = set(sources)
        if SITE_SOURCE + "/index.md" not in self.known:
            raise BuildError(f"{SITE_SOURCE}/index.md is missing")
        for source in sources:
            text = (self.repo / source).read_text(encoding="utf-8")
            if "{{capture:config-explain}}" in text:
                text = text.replace("{{capture:config-explain}}", self.capture())
            renderer = Renderer(source, self.resolve)
            body = renderer.render(text)
            self.pages[source] = {"out": self.out_path(source), "title": renderer.title or Path(source).stem, "html": body, "ids": renderer.ids}
        if self.errors:
            raise BuildError("broken links:\n  " + "\n  ".join(sorted(set(self.errors))))

        if self.out.exists():
            shutil.rmtree(self.out)
        self.out.mkdir(parents=True)
        shutil.copyfile(TEMPLATES / "site.css", self.out / "site.css")
        shutil.copyfile(TEMPLATES / "load.html", self.out / "load.html")
        template = string.Template((TEMPLATES / "page.html").read_text(encoding="utf-8"))
        for source, page in self.pages.items():
            target = self.out / page["out"]
            target.parent.mkdir(parents=True, exist_ok=True)
            depth = len(Path(page["out"]).parts) - 1
            root = "/".join([".."] * depth) if depth else "."
            title = page["title"] if page["out"] == "index.html" else f"{page['title']} | stratarc"
            target.write_text(
                template.substitute(title=html.escape(title), root=root, nav=self.nav(page["out"]), body=page["html"]),
                encoding="utf-8",
            )

    def nav(self, current: str) -> str:
        def link(source: str, label: str) -> str:
            page = self.pages[source]
            href = posixpath.relpath(page["out"], posixpath.dirname(current) or ".")
            mark = ' aria-current="page"' if page["out"] == current else ""
            return f'<li><a href="{html.escape(href)}"{mark}>{html.escape(label)}</a></li>'

        home = posixpath.relpath("index.html", posixpath.dirname(current) or ".")
        first = posixpath.relpath("load.html", posixpath.dirname(current) or ".")
        parts = [f'<ul><li><a href="{home}"' + (' aria-current="page"' if current == "index.html" else "") + f'>home</a></li><li><a href="{first}">first run</a></li></ul>']
        for section, heading in SECTIONS:
            members = [s for s in self.pages if s.startswith(section + "/") and not s.startswith(SITE_SOURCE + "/")]
            if not members:
                continue

            def rank(source: str) -> tuple:
                rest = Path(source).relative_to(section)
                group = rest.parts[0] if len(rest.parts) > 1 else ""
                order = QUADRANTS.index(group) if group in QUADRANTS else (-1 if not group else len(QUADRANTS))
                return (order, group, rest.name != "README.md", str(rest))

            members.sort(key=rank)
            parts.append(f"<h2>{html.escape(heading)}</h2>")
            items = []
            for source in members:
                rest = Path(source).relative_to(section)
                if rest.name == "README.md":
                    label = "overview" if len(rest.parts) == 1 else "/".join(rest.parts[:-1])
                else:
                    label = self.pages[source]["title"]
                    if len(rest.parts) > 2:
                        label = "/".join(rest.parts[1:-1]) + ": " + label
                items.append(link(source, label))
            parts.append("<ul>" + "".join(items) + "</ul>")
        return "\n".join(parts)


def build_site(repo: Path, out: Path) -> Site:
    site = Site(repo, out)
    site.build()
    return site


# ----- command line -----


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="build_site.py", description="Build the documentation site, or check its generated pages.")
    parser.add_argument("--repo", metavar="PATH", default=str(ENGINE_ROOT), help="the repository whose docs/ and developer-docs/ are read (default: this repository)")
    parser.add_argument("--out", metavar="DIR", help="where to build the site (default: site/ under the repository)")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="exit 6 when a committed generated page differs from the code; build nothing")
    mode.add_argument("--write-generated", action="store_true", help="rewrite the committed generated pages from the code; build nothing")
    try:
        args = parser.parse_args(argv)
    except SystemExit as stop:
        return 0 if stop.code in (0, None) else 2
    repo = Path(args.repo).resolve()
    if not repo.is_dir():
        print(f"error: {repo} is not a directory", file=sys.stderr)
        return 2
    sys.path.insert(0, str(ENGINE_ROOT))
    try:
        if args.check:
            stale = check_generated(repo)
            for rel in stale:
                print(f"stale: {rel}", file=sys.stderr)
            if stale:
                print("run: python3 scripts/docs/build_site.py --write-generated", file=sys.stderr)
                return 6
            print("generated pages match the code")
            return 0
        if args.write_generated:
            for rel in write_generated(repo):
                print(f"wrote {rel}")
            return 0
        out = Path(args.out).resolve() if args.out else repo / "site"
        site = build_site(repo, out)
    except BuildError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    print(f"built {len(site.pages)} pages into {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
