"""Render user-scope rules into one digest block.

Only some runtimes load a rule tree on their own. The others read a single
instruction file and never see the rules, so rule content reaches them via ONE
generated digest block with a single source of truth (the rule tree), never by
hand-copied duplication. This module builds that block; the adapter generators
append it to every generated instruction file, and `stratarc gen-rules-digest`
embeds and refreshes it between markers in hand-authored surface files (for
example a runtime's user-level AGENTS.md).

Rendering is deterministic: each selected rule renders as its `## binding`
section plus a pointer to the full rule in the canonical source tree, on every
runtime. A rule with no binding section renders whole, with its frontmatter
stripped, its H1 dropped and its remaining headings demoted two levels so they
nest under the per-rule H3. Full bodies on every surface, plus Claude Code
loading the deployed rule tree beside them, pushed sessions past Claude Code's
150k-character instruction limit.

Source root rendering: rule text spells the source checkout as the token
`${STRATARC_SOURCE}`, never as a path, because the rules may be published, and
so does the digest by default: its `Full rule:` pointers open with
`${STRATARC_SOURCE}/rules/`, so the committed AGENTS.md digest is the same on
every machine. The token becomes a path only at deploy time, when a caller
names the root the render is for (build_rules_digest's source_root, which
render_source applies to the binding text and rules_prefix to the pointers):
stratarc.staging renders every staged rule and AGENTS.md that way, and
stratarc.sync renders the gitignored CLAUDE.md, CODEX.md and GEMINI.md it
refreshes beside AGENTS.md.

Tier selection: `rules/tiers.json` maps every rule file to exactly one
of three tiers (global, common, project). Without a `column`, the digest
renders the full global tier plus the full common tier: this is the fixed set
the five hand-authored runtime instruction files carry, and it does not read
control-plane.md, so the digest keeps working with no live tree. With a
`column` (a control-plane.md project name), the digest instead follows that
column's own opt-ins: a global-tier rule renders unconditionally (it cannot be
opted out), a common- or project-tier rule renders only when that column's
`rule:<name>` cell is opted in.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from stratarc.control_plane import ControlPlane
from stratarc.paths import home, source_root

DIGEST_SOURCE_ENV_VAR = "RULES_DIGEST_SOURCE"

DIGEST_BEGIN = (
    "<!-- BEGIN RULES-DIGEST generated by stratarc gen-rules-digest "
    "-- do not hand-edit between markers -->"
)
DIGEST_END = "<!-- END RULES-DIGEST -->"

TIER_ORDER = ("global", "common", "project")

# The token rule text, and the committed digest, use for the source root.
# Rule source never carries one machine's checkout path; the token is
# rendered to a real path at deploy time only (stratarc.staging for staged
# copies, stratarc.sync for the generated instruction files beside AGENTS.md).
# The variable of the same name is what stratarc.sync exports to the scripts
# it runs.
SOURCE_TOKEN = "${STRATARC_SOURCE}"


def render_root(root: str | Path) -> str:
    """The source root as a pointer spells it: `$HOME/<rel>` under the home
    directory, the absolute path elsewhere.

    The committed digest and every managed project's CLAUDE.md carried the
    `$HOME` spelling before the token existed, so rendering the same way
    keeps them byte-identical and keeps the user name out of
    text other checkouts read. The root is compared as given, unresolved, so
    a caller that already resolved it gets the resolved spelling back.
    """
    root = Path(root).expanduser()
    try:
        relative = root.relative_to(home())
    except ValueError:
        return str(root)
    return "$HOME" if relative == Path(".") else f"$HOME/{relative.as_posix()}"


def render_source(text: str, root: str | Path) -> str:
    """*text* with every SOURCE_TOKEN replaced by render_root(root)."""
    if SOURCE_TOKEN not in text:
        return text
    return text.replace(SOURCE_TOKEN, render_root(root))


def rules_prefix(root: str | Path) -> str:
    """Where a digest's pointers send a reader for a rule's full text: the
    rules/ directory of the source root the digest was rendered for."""
    return render_root(root) + "/rules/"


# The pointer prefix a digest carries by default: the token form, so the
# committed digest names no machine. A digest rendered for a root
# (build_rules_digest's source_root) carries rules_prefix(root) instead.
CANONICAL_RULES_PREFIX = SOURCE_TOKEN + "/rules/"

_MISSING_TREE_NOTE = (
    "User-scope rules digest unavailable: canonical rule tree not found. "
    "The canonical source is `rules/` with its `tiers.json` in the source root."
)


def resolve_rules_root(rules_root: str | Path | None = None) -> Path:
    """Resolve the digest source: explicit arg, then env override, then the source root's `rules/`."""
    if rules_root is not None:
        return Path(rules_root).expanduser()
    env = os.environ.get(DIGEST_SOURCE_ENV_VAR)
    if env:
        return Path(env).expanduser()
    return source_root() / "rules"


def _strip_frontmatter(text: str) -> str:
    """Drop a leading YAML frontmatter fence; return the body unchanged otherwise."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return text
    for idx in range(1, len(lines)):
        if lines[idx].strip() == "---":
            return "\n".join(lines[idx + 1 :]).lstrip("\n")
    return text


def _extract_binding_section(text: str) -> str:
    """Extract the binding section (from ## binding to the next ##, or EOF).

    Returns the binding section text (without the ## binding heading itself),
    or an empty string if no binding section exists. Extraction is fence-aware:
    code fences prevent the next ## from terminating the binding section.
    """
    body = _strip_frontmatter(text)
    lines = body.split("\n")
    binding_start = None
    in_fence = False
    for idx, line in enumerate(lines):
        stripped = line.lstrip()
        if stripped.startswith("```"):
            in_fence = not in_fence
        if not in_fence and line.rstrip() == "## binding":
            binding_start = idx + 1
            break
    if binding_start is None:
        return ""
    binding_lines = []
    in_fence = False
    for line in lines[binding_start:]:
        stripped = line.lstrip()
        if stripped.startswith("```"):
            in_fence = not in_fence
            binding_lines.append(line)
            continue
        if not in_fence and line.startswith("##"):
            break
        binding_lines.append(line)
    return "\n".join(binding_lines).strip("\n")


def _render_rule_body(text: str) -> str:
    """Strip frontmatter and the H1, demote remaining headings by two levels.

    Demotion is fence-aware: heading-shaped lines inside ``` code fences are
    left untouched.
    """
    body = _strip_frontmatter(text)
    out: list[str] = []
    in_fence = False
    for line in body.split("\n"):
        stripped = line.lstrip()
        if stripped.startswith("```"):
            in_fence = not in_fence
            out.append(line)
            continue
        if not in_fence and line.startswith("#"):
            if line.startswith("# "):
                # The H1 repeats the filename stem; the digest's per-rule
                # heading already carries it.
                continue
            out.append("##" + line)
            continue
        out.append(line)
    return "\n".join(out).strip("\n")


def load_tiers(root: Path) -> dict[str, list[str]]:
    """Load rules/tiers.json under *root*: tier name to rule filenames.

    Returns an empty mapping when the manifest is absent or not a JSON
    object, so a caller degrades to "no rules selected" instead of raising.
    Non-list tier values are dropped rather than raising, since a malformed
    manifest is the source validator's rule-tier check to flag, not this
    module's.
    """
    path = root / "tiers.json"
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    if not isinstance(data, dict):
        return {}
    return {
        str(tier): [str(name) for name in names]
        for tier, names in data.items()
        if isinstance(names, list)
    }


def _tiered_rules(
    root: Path, tiers: dict[str, list[str]], wanted: tuple[str, ...]
) -> list[tuple[str, Path]]:
    """(tier, path) pairs for manifest entries whose tier is in *wanted*.

    Tier order first, then alphabetical (case-insensitive) within a tier. A
    manifest entry naming a file that is not on disk is skipped rather than
    raising; that mismatch is the source validator's rule-tier check to report.
    """
    selected: list[tuple[str, Path]] = []
    for tier in wanted:
        for name in sorted(tiers.get(tier, []), key=str.casefold):
            candidate = root / name
            if candidate.is_file():
                selected.append((tier, candidate))
    return selected


def _selected_rules(
    root: Path,
    column: str | None = None,
    control_plane_path: Path | None = None,
) -> list[tuple[str, Path]]:
    """(tier, path) pairs to render, per the module docstring's tier rules."""
    tiers = load_tiers(root)
    if not tiers:
        return []
    if column is None:
        return _tiered_rules(root, tiers, ("global", "common"))

    # Column-scoped: read control-plane.md's opt-ins for this column.
    cp = (
        ControlPlane.load(control_plane_path)
        if control_plane_path is not None
        else ControlPlane.load()
    )
    opted_in = cp.enabled_ids(column, "rule:")
    selected: list[tuple[str, Path]] = []
    for tier in TIER_ORDER:
        for name in sorted(tiers.get(tier, []), key=str.casefold):
            stem = Path(name).stem
            if tier != "global" and stem not in opted_in:
                continue
            candidate = root / name
            if candidate.is_file():
                selected.append((tier, candidate))
    return selected


def build_rules_digest(
    rules_root: str | Path | None = None,
    column: str | None = None,
    control_plane_path: str | Path | None = None,
    pointer_prefix: str | None = None,
    source_root: str | Path | None = None,
) -> str | None:
    """Return the digest block (markers included), or None if unavailable.

    None means either the source tree is absent (e.g. CI with no checkout) or rules/tiers.json selects nothing to render; callers degrade to a
    pointer note rather than fabricating rule content.

    Each rule renders as its binding section plus a pointer line naming
    pointer_prefix + its filename; a rule with no binding section renders in
    full, since a pointer alone would drop its requirement. The rule
    selection is the same whatever pointer_prefix is.

    Without source_root the digest is portable: every SOURCE_TOKEN in the
    rule text stays as written and the pointers open with
    CANONICAL_RULES_PREFIX, the token form. With source_root, the checkout
    the digest is deployed for, every token becomes that root and
    pointer_prefix defaults to its rules/ directory.
    """
    root = resolve_rules_root(rules_root)
    if not root.is_dir():
        return None
    cp_path = Path(control_plane_path) if control_plane_path is not None else None
    rules = _selected_rules(root, column=column, control_plane_path=cp_path)
    if not rules:
        return None
    if pointer_prefix is None:
        pointer_prefix = (
            CANONICAL_RULES_PREFIX if source_root is None else rules_prefix(source_root)
        )
    parts = [
        DIGEST_BEGIN,
        "",
        "## user-scope-rules-digest",
        "",
        (
            "Rendered from the canonical rule tree (`rules/` in the source root) per "
            "`rules/tiers.json`: each rule's binding section and a pointer to "
            "its full text. These rules are binding on every agent surface; "
            "read the full rule when a task turns on its detail. Edit the "
            "source rules and re-run `stratarc gen-rules-digest`; "
            "hand-edits between the markers are overwritten."
        ),
        "",
    ]
    for tier, path in rules:
        # Headings stay kebab-case under markdown-style; the tier moves into
        # the first body line so the information survives.
        parts.append(f"### {path.stem}")
        parts.append("")
        parts.append(f"Tier: {tier}.")
        parts.append("")
        text = path.read_text(encoding="utf-8")
        if source_root is not None:
            text = render_source(text, source_root)
        binding = _extract_binding_section(text)
        if binding:
            parts.append(binding)
            parts.append("")
            parts.append(f"Full rule: `{pointer_prefix}{path.name}`")
        else:
            parts.append(_render_rule_body(text))
        parts.append("")
    parts.append(DIGEST_END)
    return "\n".join(parts)


def digest_or_note(
    rules_root: str | Path | None = None,
    column: str | None = None,
    control_plane_path: str | Path | None = None,
    pointer_prefix: str | None = None,
    source_root: str | Path | None = None,
) -> str:
    """Digest block, or the degraded pointer note when nothing is available."""
    digest = build_rules_digest(
        rules_root,
        column=column,
        control_plane_path=control_plane_path,
        pointer_prefix=pointer_prefix,
        source_root=source_root,
    )
    return digest if digest is not None else _MISSING_TREE_NOTE


def embed_digest(document: str, digest: str) -> str:
    """Replace the marker-delimited region of *document* with *digest*.

    Raises ValueError when the markers are missing or malformed, so an embed
    against an unprepared file fails loudly instead of appending silently.
    """
    begin = document.find(DIGEST_BEGIN)
    end = document.find(DIGEST_END)
    if begin == -1 or end == -1 or end < begin:
        raise ValueError(
            "document has no well-formed RULES-DIGEST marker pair; add "
            f"{DIGEST_BEGIN!r} and {DIGEST_END!r} where the digest belongs"
        )
    return document[:begin] + digest + document[end + len(DIGEST_END) :]
