"""Embed the user-scope rules digest into hand-authored surface files.

Renders the user-scope rules digest and embeds it into instruction files.
This CLI serves the hand-authored surfaces (a runtime's user-level
AGENTS.md, project AGENTS.md files): it renders the digest from the canonical rule tree and
replaces the marker-delimited region in each target, with a `--check` drift
gate the targets' CI can adopt.

The target file must already contain the marker pair; embedding never appends
to an unprepared file. Add the markers once, where the digest belongs:

  <!-- BEGIN RULES-DIGEST generated by agentrc gen-rules-digest -- do not hand-edit between markers -->
  <!-- END RULES-DIGEST -->

Usage:
  agentrc gen-rules-digest --print                       # digest to stdout
  agentrc gen-rules-digest --embed FILE [FILE ...]       # refresh digest in targets
  agentrc gen-rules-digest --check FILE [FILE ...]       # exit non-zero on drift
  agentrc gen-rules-digest --rules-root DIR ...          # override the source tree
  agentrc gen-rules-digest --prefix TEXT ...             # override the Full rule: pointer prefix
  agentrc gen-rules-digest --source-root DIR ...         # deploy-time render: every ${AGENTRC_SOURCE}
                                                      # in the digest and the target becomes DIR
  agentrc gen-rules-digest --column NAME ...             # render one control-plane column;
                                                      # without it, the global tier plus the
                                                      # common tier renders, unconditionally

By default the digest is portable: rule text spells the source checkout as
`${AGENTRC_SOURCE}` and the `Full rule:` pointers open with
`${AGENTRC_SOURCE}/rules/`, so the committed AGENTS.md names no machine. With
--source-root the digest, and the whole of each --embed or --check target, is
rendered for that checkout: the token becomes its path (`$HOME/...` under the
home directory) and the pointers name its rules/ directory. agentrc sync
embeds every target without it and then renders the gitignored CLAUDE.md,
CODEX.md and GEMINI.md in place, so the committed AGENTS.md stays portable.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from agentrc.control_plane import ControlPlane
from agentrc.rules_digest import (
    build_rules_digest,
    embed_digest,
    render_source,
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="agentrc gen-rules-digest", description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--print",
        action="store_true",
        dest="print_digest",
        help="Write the rendered digest block to stdout.",
    )
    mode.add_argument(
        "--embed",
        nargs="+",
        type=Path,
        metavar="FILE",
        help="Replace the marker-delimited digest in each FILE.",
    )
    mode.add_argument(
        "--check",
        nargs="+",
        type=Path,
        metavar="FILE",
        help="Exit non-zero if any FILE's digest has drifted.",
    )
    parser.add_argument(
        "--rules-root",
        type=Path,
        default=None,
        help=(
            "Rule tree to render (default: $RULES_DIGEST_SOURCE, else the "
            "source root's rules/, which carries tiers.json)."
        ),
    )
    parser.add_argument(
        "--prefix",
        default=None,
        help=(
            "Text the Full rule: pointers open with (default: "
            "${AGENTRC_SOURCE}/rules/, or the rules/ directory of "
            "--source-root when given)."
        ),
    )
    parser.add_argument(
        "--source-root",
        type=Path,
        default=None,
        help=(
            "Render for this checkout: every ${AGENTRC_SOURCE} in the digest "
            "and in each target becomes this path. Deploy time only; the "
            "committed AGENTS.md keeps the token."
        ),
    )
    parser.add_argument(
        "--column",
        default=None,
        help=(
            "Render this control-plane.md column's opt-ins instead of the "
            "global tier plus the common tier. Read from the source root's "
            "control-plane.md."
        ),
    )
    args = parser.parse_args(argv)
    source_root = (
        args.source_root.expanduser().resolve() if args.source_root is not None else None
    )

    if args.column is not None:
        cp = ControlPlane.load()
        if args.column not in cp.columns:
            known = ", ".join(cp.columns) or "(none)"
            print(
                f"gen-rules-digest: unknown column {args.column!r}; known columns: {known}",
                file=sys.stderr,
            )
            return 1

    digest = build_rules_digest(
        args.rules_root,
        column=args.column,
        pointer_prefix=args.prefix,
        source_root=source_root,
    )
    if digest is None:
        print("gen-rules-digest: no rule tree found to render", file=sys.stderr)
        return 1

    if args.print_digest:
        print(digest)
        return 0

    targets = args.embed if args.embed else args.check
    failures: list[str] = []
    for target in targets:
        try:
            document = target.read_text(encoding="utf-8")
        except OSError as exc:
            failures.append(f"{target}: {exc}")
            continue
        try:
            updated = embed_digest(document, digest)
        except ValueError as exc:
            failures.append(f"{target}: {exc}")
            continue
        if source_root is not None:
            updated = render_source(updated, source_root)
        if args.check:
            if updated != document:
                failures.append(f"{target}: digest is stale; re-run --embed")
            continue
        if updated != document:
            target.write_text(updated, encoding="utf-8")
            print(f"gen-rules-digest: refreshed digest in {target}")
        else:
            print(f"gen-rules-digest: {target} already current")

    if failures:
        for failure in failures:
            print(f"gen-rules-digest: {failure}", file=sys.stderr)
        return 1
    if args.check:
        print("gen-rules-digest: all targets in sync with the rule tree.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
